services:
  api:
    # build: .
    image: minawm/baby-sleep:v2
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app    
    environment:
      - YOLO_CONFIG_DIR=/app/configs
    command: ["bash", "-c", "source activate server_conda && fastapi dev main.py --host 0.0.0.0 --port 8000"]
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
